name       : hunspell-de
version    : 20151222
release    : 2
source     :
    - https://www.j3e.de/ispell/igerman98/dict/igerman98-20151222.tar.bz2 : 5964178dc87b9be9dfe7cb256c2e35e139e86063225c19cb1fe2cc7cb11d7e4e
license    : GPL-3.0
component  : spelling
summary    : German hunspell dictionaries
description: |
    German hunspell dictionaries
builddeps  :
    - ispell
    - libhunspell
rundeps    :
    - libhunspell
build      : |
    export LC_ALL=C
    export LANG=C
    make hunspell/de_AT.dic hunspell/de_AT.aff \
        hunspell/de_CH.dic hunspell/de_CH.aff \
        hunspell/de_DE.dic hunspell/de_DE.aff -j1
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    install -m 00644 hunspell/de_??.dic $installdir/usr/share/hunspell
    install -m 00644 hunspell/de_??.aff $installdir/usr/share/hunspell

    pushd $installdir/usr/share/hunspell
    ln -s de_DE.dic de_BE.dic
    ln -s de_DE.aff de_BE.aff
    ln -s de_DE.dic de_LU.dic
    ln -s de_DE.aff de_LU.aff
    ln -s de_CH.dic de_LI.dic
    ln -s de_CH.aff de_LI.aff
    popd
